# Run Travis CI using Rocker Project containers

language: c
sudo: required
dist: focal
services: docker

jobs:
  include:
    - name: dev
      env: DOCKER_CNTR="rocker/drd"

env:
  global:
    - DOCKER_OPTS="--rm -ti -v $(pwd):/mnt -w /mnt"
      
install:
  - docker pull ${DOCKER_CNTR}

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} /mnt/scripts/ci.sh

notifications:
  email:
    on_success: change
    on_failure: change

