# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c
sudo: required
dist: bionic

## Two core settings: BSPM for binary installation where possible, and no
## installation of 'Suggests:' to keep things lighter.
##
## We also add edd/r-4.0 as it contains three binary packages (RcppDate,
## RcppCCTZ, nanotime) used by the tiledb package. This is optional.
env:
  global:
    - USE_BSPM="true"
    - _R_CHECK_FORCE_SUGGESTS_="false"
    - ADDED_PPAS="ppa:edd/r-4.0"

## Install the worker script and use it to set things up
before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

## Take care of dependencies (via remotes::install_deps which feeds into
## BSPM-enabled install.packages(); also install_all installs Suggests:
## too, and install_r can install named packages from known repos 
install:
  - ./run.sh install_deps

## Run tests  
script:
  - ./run.sh run_tests

## Dump logs of failed
after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
  
