# Run Travis CI using Rocker Project containers

language: c
sudo: required
dist: focal
services: docker

jobs:
  include:
    - name: rel
      env: DOCKER_CNTR="rocker/r-base" JOB="rel"
    #- name: dev
    #  env: DOCKER_CNTR="rocker/drd" JOB="dev"

env:
  global:
    - DOCKER_OPTS="--rm -ti -v $(pwd):/mnt -w /mnt"
      
install:
  - docker pull ${DOCKER_CNTR}

script:
  - if [[ "$JOB" == "dev" ]]; then docker run ${DOCKER_OPTS} ${DOCKER_CNTR} /mnt/scripts/ciDev.sh; fi
  - if [[ "$JOB" == "rel" ]]; then docker run ${DOCKER_OPTS} ${DOCKER_CNTR} /mnt/scripts/ciRel.sh; fi

notifications:
  email:
    on_success: change
    on_failure: change

