// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// remap_indices
Rcpp::List remap_indices(Rcpp::List starts, Rcpp::List ends, Rcpp::List positions);
RcppExport SEXP _TileDBArray_remap_indices(SEXP startsSEXP, SEXP endsSEXP, SEXP positionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type positions(positionsSEXP);
    rcpp_result_gen = Rcpp::wrap(remap_indices(starts, ends, positions));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TileDBArray_remap_indices", (DL_FUNC) &_TileDBArray_remap_indices, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TileDBArray(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
