// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// remap_indices
Rcpp::List remap_indices(Rcpp::List extracted, Rcpp::List remapping);
RcppExport SEXP _TileDBArray_remap_indices(SEXP extractedSEXP, SEXP remappingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type extracted(extractedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type remapping(remappingSEXP);
    rcpp_result_gen = Rcpp::wrap(remap_indices(extracted, remapping));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TileDBArray_remap_indices", (DL_FUNC) &_TileDBArray_remap_indices, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TileDBArray(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
