# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

remap_indices <- function(starts, ends, positions) {
    .Call('_TileDBArray_remap_indices', PACKAGE = 'TileDBArray', starts, ends, positions)
}

